import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { getServerSession } from "next-auth";
import { authOptions } from "~/server/auth";
import { TRPCReactProvider } from "~/trpc/react";
import SessionProviderClientComponent from "./(auth)/_components/session-provider-client-component";


export const metadata = {
  title: "Artisanal's AI Agent",
  description: "Generated by create-t3-app",
};
// icons: [{ rel: "icon", url: "/favicon.ico" }],

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <SessionProviderClientComponent session={session}>
          <TRPCReactProvider>{children}</TRPCReactProvider>
        </SessionProviderClientComponent>
      </body>
    </html>
  );
}
